# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comport.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(1096, 512)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainForm.sizePolicy().hasHeightForWidth())
        MainForm.setSizePolicy(sizePolicy)
        MainForm.setMinimumSize(QtCore.QSize(350, 512))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainForm.setFont(font)
        self.groupBox_Comport = QtWidgets.QGroupBox(MainForm)
        self.groupBox_Comport.setGeometry(QtCore.QRect(10, 20, 141, 151))
        self.groupBox_Comport.setMinimumSize(QtCore.QSize(141, 151))
        self.groupBox_Comport.setObjectName("groupBox_Comport")
        self.comboBox_ComPort = QtWidgets.QComboBox(self.groupBox_Comport)
        self.comboBox_ComPort.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.comboBox_ComPort.setObjectName("comboBox_ComPort")
        self.comboBox_BaudRate = QtWidgets.QComboBox(self.groupBox_Comport)
        self.comboBox_BaudRate.setGeometry(QtCore.QRect(10, 60, 121, 31))
        self.comboBox_BaudRate.setStyleSheet("")
        self.comboBox_BaudRate.setObjectName("comboBox_BaudRate")
        self.comboBox_BaudRate.addItem("")
        self.comboBox_BaudRate.addItem("")
        self.comboBox_BaudRate.addItem("")
        self.pushButton_Connect = QtWidgets.QPushButton(self.groupBox_Comport)
        self.pushButton_Connect.setGeometry(QtCore.QRect(10, 100, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Connect.sizePolicy().hasHeightForWidth())
        self.pushButton_Connect.setSizePolicy(sizePolicy)
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.textEdit_hex = QtWidgets.QTextEdit(MainForm)
        self.textEdit_hex.setEnabled(True)
        self.textEdit_hex.setGeometry(QtCore.QRect(160, 30, 631, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.textEdit_hex.sizePolicy().hasHeightForWidth())
        self.textEdit_hex.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_hex.setFont(font)
        self.textEdit_hex.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_hex.setReadOnly(True)
        self.textEdit_hex.setObjectName("textEdit_hex")
        self.textEdit_ascii = QtWidgets.QTextEdit(MainForm)
        self.textEdit_ascii.setEnabled(True)
        self.textEdit_ascii.setGeometry(QtCore.QRect(800, 30, 291, 341))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_ascii.setFont(font)
        self.textEdit_ascii.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_ascii.setReadOnly(True)
        self.textEdit_ascii.setObjectName("textEdit_ascii")
        self.groupBox_Setting = QtWidgets.QGroupBox(MainForm)
        self.groupBox_Setting.setGeometry(QtCore.QRect(10, 180, 141, 191))
        self.groupBox_Setting.setMinimumSize(QtCore.QSize(141, 0))
        self.groupBox_Setting.setObjectName("groupBox_Setting")
        self.pushButton_Clear = QtWidgets.QPushButton(self.groupBox_Setting)
        self.pushButton_Clear.setGeometry(QtCore.QRect(10, 20, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Clear.sizePolicy().hasHeightForWidth())
        self.pushButton_Clear.setSizePolicy(sizePolicy)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox_Setting)
        self.pushButton_Stop.setGeometry(QtCore.QRect(10, 70, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Stop.sizePolicy().hasHeightForWidth())
        self.pushButton_Stop.setSizePolicy(sizePolicy)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.label = QtWidgets.QLabel(self.groupBox_Setting)
        self.label.setGeometry(QtCore.QRect(10, 120, 71, 21))
        self.label.setObjectName("label")
        self.spinBox_FontSize = QtWidgets.QSpinBox(self.groupBox_Setting)
        self.spinBox_FontSize.setGeometry(QtCore.QRect(80, 120, 51, 22))
        self.spinBox_FontSize.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_FontSize.setMinimum(6)
        self.spinBox_FontSize.setProperty("value", 10)
        self.spinBox_FontSize.setObjectName("spinBox_FontSize")
        self.radioButton_Text_Hex = QtWidgets.QRadioButton(self.groupBox_Setting)
        self.radioButton_Text_Hex.setGeometry(QtCore.QRect(10, 150, 61, 31))
        self.radioButton_Text_Hex.setChecked(True)
        self.radioButton_Text_Hex.setObjectName("radioButton_Text_Hex")
        self.radioButton_Text_Ascii = QtWidgets.QRadioButton(self.groupBox_Setting)
        self.radioButton_Text_Ascii.setGeometry(QtCore.QRect(70, 150, 75, 31))
        self.radioButton_Text_Ascii.setObjectName("radioButton_Text_Ascii")
        self.groupBox_Tx = QtWidgets.QGroupBox(MainForm)
        self.groupBox_Tx.setEnabled(True)
        self.groupBox_Tx.setGeometry(QtCore.QRect(10, 380, 1061, 121))
        self.groupBox_Tx.setMinimumSize(QtCore.QSize(0, 121))
        self.groupBox_Tx.setObjectName("groupBox_Tx")
        self.lineEdit_Tx = QtWidgets.QLineEdit(self.groupBox_Tx)
        self.lineEdit_Tx.setGeometry(QtCore.QRect(10, 40, 961, 31))
        self.lineEdit_Tx.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Tx.setFont(font)
        self.lineEdit_Tx.setObjectName("lineEdit_Tx")
        self.pushButton_Tx_Send = QtWidgets.QPushButton(self.groupBox_Tx)
        self.pushButton_Tx_Send.setGeometry(QtCore.QRect(10, 80, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Tx_Send.sizePolicy().hasHeightForWidth())
        self.pushButton_Tx_Send.setSizePolicy(sizePolicy)
        self.pushButton_Tx_Send.setObjectName("pushButton_Tx_Send")
        self.pushButton_Tx_Clear = QtWidgets.QPushButton(self.groupBox_Tx)
        self.pushButton_Tx_Clear.setGeometry(QtCore.QRect(110, 80, 91, 31))
        self.pushButton_Tx_Clear.setObjectName("pushButton_Tx_Clear")
        self.radioButton_Ascii = QtWidgets.QRadioButton(self.groupBox_Tx)
        self.radioButton_Ascii.setGeometry(QtCore.QRect(310, 80, 75, 31))
        self.radioButton_Ascii.setObjectName("radioButton_Ascii")
        self.radioButton_Hex = QtWidgets.QRadioButton(self.groupBox_Tx)
        self.radioButton_Hex.setGeometry(QtCore.QRect(250, 80, 61, 31))
        self.radioButton_Hex.setChecked(True)
        self.radioButton_Hex.setObjectName("radioButton_Hex")
        self.label_Tx_HexNum = QtWidgets.QLabel(self.groupBox_Tx)
        self.label_Tx_HexNum.setEnabled(False)
        self.label_Tx_HexNum.setGeometry(QtCore.QRect(13, 20, 961, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Tx_HexNum.setFont(font)
        self.label_Tx_HexNum.setObjectName("label_Tx_HexNum")
        self.label_HexPos = QtWidgets.QLabel(MainForm)
        self.label_HexPos.setEnabled(False)
        self.label_HexPos.setGeometry(QtCore.QRect(165, 10, 921, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_HexPos.setFont(font)
        self.label_HexPos.setObjectName("label_HexPos")
        self.label_HexPos.raise_()
        self.groupBox_Comport.raise_()
        self.textEdit_hex.raise_()
        self.textEdit_ascii.raise_()
        self.groupBox_Setting.raise_()
        self.groupBox_Tx.raise_()

        self.retranslateUi(MainForm)
        self.comboBox_BaudRate.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Com Port"))
        self.groupBox_Comport.setTitle(_translate("MainForm", "Com Port"))
        self.comboBox_BaudRate.setItemText(0, _translate("MainForm", "9600"))
        self.comboBox_BaudRate.setItemText(1, _translate("MainForm", "57600"))
        self.comboBox_BaudRate.setItemText(2, _translate("MainForm", "115200"))
        self.pushButton_Connect.setText(_translate("MainForm", "Disconnected"))
        self.groupBox_Setting.setTitle(_translate("MainForm", "Setting"))
        self.pushButton_Clear.setText(_translate("MainForm", "Clear"))
        self.pushButton_Stop.setText(_translate("MainForm", "Reading"))
        self.label.setText(_translate("MainForm", "Font Size"))
        self.radioButton_Text_Hex.setText(_translate("MainForm", "Hex"))
        self.radioButton_Text_Ascii.setText(_translate("MainForm", "ASCII"))
        self.groupBox_Tx.setTitle(_translate("MainForm", "Tx"))
        self.pushButton_Tx_Send.setText(_translate("MainForm", "Send"))
        self.pushButton_Tx_Clear.setText(_translate("MainForm", "Clear"))
        self.radioButton_Ascii.setText(_translate("MainForm", "ASCII"))
        self.radioButton_Hex.setText(_translate("MainForm", "Hex"))
        self.label_Tx_HexNum.setText(_translate("MainForm", "00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 10 11 12 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F"))
        self.label_HexPos.setText(_translate("MainForm", "00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 10 11 12 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QWidget()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec_())
