# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form/comport_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_ComPortSetting(object):
    def setupUi(self, Form_ComPortSetting):
        Form_ComPortSetting.setObjectName("Form_ComPortSetting")
        Form_ComPortSetting.resize(307, 171)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Form_ComPortSetting.setFont(font)
        self.groupBox_Comport0 = QtWidgets.QGroupBox(Form_ComPortSetting)
        self.groupBox_Comport0.setGeometry(QtCore.QRect(0, 0, 141, 151))
        self.groupBox_Comport0.setMinimumSize(QtCore.QSize(141, 151))
        self.groupBox_Comport0.setObjectName("groupBox_Comport0")
        self.comboBox_ComPort0 = QtWidgets.QComboBox(self.groupBox_Comport0)
        self.comboBox_ComPort0.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.comboBox_ComPort0.setObjectName("comboBox_ComPort0")
        self.comboBox_BaudRate0 = QtWidgets.QComboBox(self.groupBox_Comport0)
        self.comboBox_BaudRate0.setGeometry(QtCore.QRect(10, 60, 121, 31))
        self.comboBox_BaudRate0.setStyleSheet("")
        self.comboBox_BaudRate0.setObjectName("comboBox_BaudRate0")
        self.comboBox_BaudRate0.addItem("")
        self.comboBox_BaudRate0.addItem("")
        self.comboBox_BaudRate0.addItem("")
        self.pushButton_Connect0 = QtWidgets.QPushButton(self.groupBox_Comport0)
        self.pushButton_Connect0.setGeometry(QtCore.QRect(10, 100, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Connect0.sizePolicy().hasHeightForWidth())
        self.pushButton_Connect0.setSizePolicy(sizePolicy)
        self.pushButton_Connect0.setObjectName("pushButton_Connect0")
        self.groupBox_Comport1 = QtWidgets.QGroupBox(Form_ComPortSetting)
        self.groupBox_Comport1.setGeometry(QtCore.QRect(150, 0, 141, 151))
        self.groupBox_Comport1.setMinimumSize(QtCore.QSize(141, 151))
        self.groupBox_Comport1.setObjectName("groupBox_Comport1")
        self.comboBox_ComPort1 = QtWidgets.QComboBox(self.groupBox_Comport1)
        self.comboBox_ComPort1.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.comboBox_ComPort1.setObjectName("comboBox_ComPort1")
        self.comboBox_BaudRate1 = QtWidgets.QComboBox(self.groupBox_Comport1)
        self.comboBox_BaudRate1.setGeometry(QtCore.QRect(10, 60, 121, 31))
        self.comboBox_BaudRate1.setStyleSheet("")
        self.comboBox_BaudRate1.setObjectName("comboBox_BaudRate1")
        self.comboBox_BaudRate1.addItem("")
        self.comboBox_BaudRate1.addItem("")
        self.comboBox_BaudRate1.addItem("")
        self.pushButton_Connect1 = QtWidgets.QPushButton(self.groupBox_Comport1)
        self.pushButton_Connect1.setGeometry(QtCore.QRect(10, 100, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Connect1.sizePolicy().hasHeightForWidth())
        self.pushButton_Connect1.setSizePolicy(sizePolicy)
        self.pushButton_Connect1.setObjectName("pushButton_Connect1")

        self.retranslateUi(Form_ComPortSetting)
        self.comboBox_BaudRate0.setCurrentIndex(2)
        self.comboBox_BaudRate1.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form_ComPortSetting)

    def retranslateUi(self, Form_ComPortSetting):
        _translate = QtCore.QCoreApplication.translate
        Form_ComPortSetting.setWindowTitle(_translate("Form_ComPortSetting", "Com Port Setting"))
        self.groupBox_Comport0.setTitle(_translate("Form_ComPortSetting", "Com Port"))
        self.comboBox_BaudRate0.setItemText(0, _translate("Form_ComPortSetting", "9600"))
        self.comboBox_BaudRate0.setItemText(1, _translate("Form_ComPortSetting", "57600"))
        self.comboBox_BaudRate0.setItemText(2, _translate("Form_ComPortSetting", "115200"))
        self.pushButton_Connect0.setText(_translate("Form_ComPortSetting", "Disconnected"))
        self.groupBox_Comport1.setTitle(_translate("Form_ComPortSetting", "Com Port"))
        self.comboBox_BaudRate1.setItemText(0, _translate("Form_ComPortSetting", "9600"))
        self.comboBox_BaudRate1.setItemText(1, _translate("Form_ComPortSetting", "57600"))
        self.comboBox_BaudRate1.setItemText(2, _translate("Form_ComPortSetting", "115200"))
        self.pushButton_Connect1.setText(_translate("Form_ComPortSetting", "Disconnected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_ComPortSetting = QtWidgets.QWidget()
    ui = Ui_Form_ComPortSetting()
    ui.setupUi(Form_ComPortSetting)
    Form_ComPortSetting.show()
    sys.exit(app.exec_())
