# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/form/message_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_message_form(object):
    def setupUi(self, message_form):
        message_form.setObjectName("message_form")
        message_form.resize(418, 346)
        self.listWidget_hotkey = QtWidgets.QListWidget(message_form)
        self.listWidget_hotkey.setGeometry(QtCore.QRect(10, 10, 391, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.listWidget_hotkey.setFont(font)
        self.listWidget_hotkey.setObjectName("listWidget_hotkey")

        self.retranslateUi(message_form)
        QtCore.QMetaObject.connectSlotsByName(message_form)

    def retranslateUi(self, message_form):
        _translate = QtCore.QCoreApplication.translate
        message_form.setWindowTitle(_translate("message_form", "Message Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    message_form = QtWidgets.QWidget()
    ui = Ui_message_form()
    ui.setupUi(message_form)
    message_form.show()
    sys.exit(app.exec_())
